<?php

namespace App\Http\Controllers;

class PageController extends Controller
{
    public function home() { return view('pages.home'); }
    public function abfluss_reinigen_baden() { return view('pages.abfluss_reinigen_baden'); }
    public function abfluss_reinigen_burgenland() { return view('pages.abfluss_reinigen_burgenland'); }
    public function abfluss_reinigen_graz() { return view('pages.abfluss_reinigen_graz'); }
    public function abfluss_reinigen_linz() { return view('pages.abfluss_reinigen_linz'); }
    public function abfluss_reinigen_niederosterreich() { return view('pages.abfluss_reinigen_niederosterreich'); }
    public function abfluss_reinigen_wien_1010() { return view('pages.abfluss_reinigen_wien_1010'); }
    public function abfluss_reinigen_wien_1020() { return view('pages.abfluss_reinigen_wien_1020'); }
    public function abfluss_reinigen_wien_1030() { return view('pages.abfluss_reinigen_wien_1030'); }
    public function abfluss_reinigen_wien_1040() { return view('pages.abfluss_reinigen_wien_1040'); }
    public function abfluss_reinigen_wien_1050() { return view('pages.abfluss_reinigen_wien_1050'); }
    public function abfluss_reinigen_wien_1060() { return view('pages.abfluss_reinigen_wien_1060'); }
    public function abfluss_reinigen_wien_1070() { return view('pages.abfluss_reinigen_wien_1070'); }
    public function abfluss_reinigen_wien_1080() { return view('pages.abfluss_reinigen_wien_1080'); }
    public function abfluss_reinigen_wien_1090() { return view('pages.abfluss_reinigen_wien_1090'); }
    public function abfluss_reinigen_wien_1100() { return view('pages.abfluss_reinigen_wien_1100'); }
    public function abfluss_reinigen_wien_1110() { return view('pages.abfluss_reinigen_wien_1110'); }
    public function abfluss_reinigen_wien_1120() { return view('pages.abfluss_reinigen_wien_1120'); }
    public function abfluss_reinigen_wien_1130() { return view('pages.abfluss_reinigen_wien_1130'); }
    public function abfluss_reinigen_wien_1140() { return view('pages.abfluss_reinigen_wien_1140'); }
    public function abfluss_reinigen_wien_1150() { return view('pages.abfluss_reinigen_wien_1150'); }
    public function abfluss_reinigen_wien_1160() { return view('pages.abfluss_reinigen_wien_1160'); }
    public function abfluss_reinigen_wien_1170() { return view('pages.abfluss_reinigen_wien_1170'); }
    public function abfluss_reinigen_wien_1180() { return view('pages.abfluss_reinigen_wien_1180'); }
    public function abfluss_reinigen_wien_1190() { return view('pages.abfluss_reinigen_wien_1190'); }
    public function abfluss_reinigen_wien_1200() { return view('pages.abfluss_reinigen_wien_1200'); }
    public function abfluss_reinigen_wien_1210() { return view('pages.abfluss_reinigen_wien_1210'); }
    public function abfluss_reinigen_wien_1220() { return view('pages.abfluss_reinigen_wien_1220'); }
    public function abfluss_reinigen_wien_1230() { return view('pages.abfluss_reinigen_wien_1230'); }
    public function abfluss_reinigen_wiener_neustadt() { return view('pages.abfluss_reinigen_wiener_neustadt'); }
    public function abfluss_stinkt() { return view('pages.abfluss_stinkt'); }
    public function abfluss_verstopft_wasser_lauft_nicht_ab() { return view('pages.abfluss_verstopft_wasser_lauft_nicht_ab'); }
    public function abfluss_verstopft_wer_zahlt_osterreich() { return view('pages.abfluss_verstopft_wer_zahlt_osterreich'); }
    public function abflussreinigung_baden() { return view('pages.abflussreinigung_baden'); }
    public function abflussreinigung_burgenland() { return view('pages.abflussreinigung_burgenland'); }
    public function abflussreinigung_graz() { return view('pages.abflussreinigung_graz'); }
    public function abflussreinigung_linz() { return view('pages.abflussreinigung_linz'); }
    public function abflussreinigung_niederosterreich() { return view('pages.abflussreinigung_niederosterreich'); }
    public function abflussreinigung_wien_1010() { return view('pages.abflussreinigung_wien_1010'); }
    public function abflussreinigung_wien_1020() { return view('pages.abflussreinigung_wien_1020'); }
    public function abflussreinigung_wien_1030() { return view('pages.abflussreinigung_wien_1030'); }
    public function abflussreinigung_wien_1040() { return view('pages.abflussreinigung_wien_1040'); }
    public function abflussreinigung_wien_1050() { return view('pages.abflussreinigung_wien_1050'); }
    public function abflussreinigung_wien_1060() { return view('pages.abflussreinigung_wien_1060'); }
    public function abflussreinigung_wien_1070() { return view('pages.abflussreinigung_wien_1070'); }
    public function abflussreinigung_wien_1080() { return view('pages.abflussreinigung_wien_1080'); }
    public function abflussreinigung_wien_1090() { return view('pages.abflussreinigung_wien_1090'); }
    public function abflussreinigung_wien_1100() { return view('pages.abflussreinigung_wien_1100'); }
    public function abflussreinigung_wien_1110() { return view('pages.abflussreinigung_wien_1110'); }
    public function abflussreinigung_wien_1120() { return view('pages.abflussreinigung_wien_1120'); }
    public function abflussreinigung_wien_1130() { return view('pages.abflussreinigung_wien_1130'); }
    public function abflussreinigung_wien_1140() { return view('pages.abflussreinigung_wien_1140'); }
    public function abflussreinigung_wien_1150() { return view('pages.abflussreinigung_wien_1150'); }
    public function abflussreinigung_wien_1160() { return view('pages.abflussreinigung_wien_1160'); }
    public function abflussreinigung_wien_1170() { return view('pages.abflussreinigung_wien_1170'); }
    public function abflussreinigung_wien_1180() { return view('pages.abflussreinigung_wien_1180'); }
    public function abflussreinigung_wien_1190() { return view('pages.abflussreinigung_wien_1190'); }
    public function abflussreinigung_wien_1200() { return view('pages.abflussreinigung_wien_1200'); }
    public function abflussreinigung_wien_1210() { return view('pages.abflussreinigung_wien_1210'); }
    public function abflussreinigung_wien_1220() { return view('pages.abflussreinigung_wien_1220'); }
    public function abflussreinigung_wien_1230() { return view('pages.abflussreinigung_wien_1230'); }
    public function abflussreinigung_wiener_neustadt() { return view('pages.abflussreinigung_wiener_neustadt'); }
    public function abflussverstopfung() { return view('pages.abflussverstopfung'); }
    public function badewanne_verstopft() { return view('pages.badewanne_verstopft'); }
    public function cookie_richtlinie() { return view('pages.cookie_richtlinie'); }
    public function dienstleistungen() { return view('pages.dienstleistungen'); }
    public function impressum() { return view('pages.impressum'); }
    public function kanalreinigung_baden() { return view('pages.kanalreinigung_baden'); }
    public function kanalreinigung_burgenland() { return view('pages.kanalreinigung_burgenland'); }
    public function kanalreinigung_graz() { return view('pages.kanalreinigung_graz'); }
    public function kanalreinigung_linz() { return view('pages.kanalreinigung_linz'); }
    public function kanalreinigung_niederosterreich() { return view('pages.kanalreinigung_niederosterreich'); }
    public function kanalreinigung_wien() { return view('pages.kanalreinigung_wien'); }
    public function kanalreinigung_wien_1010() { return view('pages.kanalreinigung_wien_1010'); }
    public function kanalreinigung_wiener_neustadt() { return view('pages.kanalreinigung_wiener_neustadt'); }
    public function kanalsanierungen() { return view('pages.kanalsanierungen'); }
    public function keller_uberflutet() { return view('pages.keller_uberflutet'); }
    public function klo_verstopft_was_tun() { return view('pages.klo_verstopft_was_tun'); }
    public function kontakt() { return view('pages.kontakt'); }
    public function kuchenabfluss_verstopft() { return view('pages.kuchenabfluss_verstopft'); }
    public function mit_backpulver_abfluss_reinigen() { return view('pages.mit_backpulver_abfluss_reinigen'); }
    public function preise() { return view('pages.preise'); }
    public function privacy_policy() { return view('pages.privacy_policy'); }
    public function privacy_policy_feed() { return view('pages.privacy_policy.feed'); }
    public function professionelle_kanalreinigung_wien_1020() { return view('pages.professionelle_kanalreinigung_wien_1020'); }
    public function professionelle_kanalreinigung_wien_1030() { return view('pages.professionelle_kanalreinigung_wien_1030'); }
    public function professionelle_kanalreinigung_wien_1040() { return view('pages.professionelle_kanalreinigung_wien_1040'); }
    public function professionelle_kanalreinigung_wien_1050() { return view('pages.professionelle_kanalreinigung_wien_1050'); }
    public function professionelle_kanalreinigung_wien_1060() { return view('pages.professionelle_kanalreinigung_wien_1060'); }
    public function professionelle_kanalreinigung_wien_1070() { return view('pages.professionelle_kanalreinigung_wien_1070'); }
    public function professionelle_kanalreinigung_wien_1080() { return view('pages.professionelle_kanalreinigung_wien_1080'); }
    public function professionelle_kanalreinigung_wien_1090() { return view('pages.professionelle_kanalreinigung_wien_1090'); }
    public function professionelle_kanalreinigung_wien_1100() { return view('pages.professionelle_kanalreinigung_wien_1100'); }
    public function professionelle_kanalreinigung_wien_1110() { return view('pages.professionelle_kanalreinigung_wien_1110'); }
    public function professionelle_kanalreinigung_wien_1120() { return view('pages.professionelle_kanalreinigung_wien_1120'); }
    public function professionelle_kanalreinigung_wien_1130() { return view('pages.professionelle_kanalreinigung_wien_1130'); }
    public function professionelle_kanalreinigung_wien_1140() { return view('pages.professionelle_kanalreinigung_wien_1140'); }
    public function professionelle_kanalreinigung_wien_1150() { return view('pages.professionelle_kanalreinigung_wien_1150'); }
    public function professionelle_kanalreinigung_wien_1160() { return view('pages.professionelle_kanalreinigung_wien_1160'); }
    public function professionelle_kanalreinigung_wien_1170() { return view('pages.professionelle_kanalreinigung_wien_1170'); }
    public function professionelle_kanalreinigung_wien_1180() { return view('pages.professionelle_kanalreinigung_wien_1180'); }
    public function professionelle_kanalreinigung_wien_1190() { return view('pages.professionelle_kanalreinigung_wien_1190'); }
    public function professionelle_kanalreinigung_wien_1200() { return view('pages.professionelle_kanalreinigung_wien_1200'); }
    public function professionelle_kanalreinigung_wien_1210() { return view('pages.professionelle_kanalreinigung_wien_1210'); }
    public function professionelle_kanalreinigung_wien_1220() { return view('pages.professionelle_kanalreinigung_wien_1220'); }
    public function professionelle_kanalreinigung_wien_1230() { return view('pages.professionelle_kanalreinigung_wien_1230'); }
    public function rohreinigung_baden() { return view('pages.rohreinigung_baden'); }
    public function rohreinigung_burgenland() { return view('pages.rohreinigung_burgenland'); }
    public function rohreinigung_graz() { return view('pages.rohreinigung_graz'); }
    public function rohreinigung_linz() { return view('pages.rohreinigung_linz'); }
    public function rohreinigung_niederosterreich() { return view('pages.rohreinigung_niederosterreich'); }
    public function rohreinigung_wien_1010() { return view('pages.rohreinigung_wien_1010'); }
    public function rohreinigung_wien_1020() { return view('pages.rohreinigung_wien_1020'); }
    public function rohreinigung_wien_1030() { return view('pages.rohreinigung_wien_1030'); }
    public function rohreinigung_wien_1040() { return view('pages.rohreinigung_wien_1040'); }
    public function rohreinigung_wien_1050() { return view('pages.rohreinigung_wien_1050'); }
    public function rohreinigung_wien_1060() { return view('pages.rohreinigung_wien_1060'); }
    public function rohreinigung_wien_1070() { return view('pages.rohreinigung_wien_1070'); }
    public function rohreinigung_wien_1080() { return view('pages.rohreinigung_wien_1080'); }
    public function rohreinigung_wien_1090() { return view('pages.rohreinigung_wien_1090'); }
    public function rohreinigung_wien_1100() { return view('pages.rohreinigung_wien_1100'); }
    public function rohreinigung_wien_1110() { return view('pages.rohreinigung_wien_1110'); }
    public function rohreinigung_wien_1120() { return view('pages.rohreinigung_wien_1120'); }
    public function rohreinigung_wien_1130() { return view('pages.rohreinigung_wien_1130'); }
    public function rohreinigung_wien_1140() { return view('pages.rohreinigung_wien_1140'); }
    public function rohreinigung_wien_1150() { return view('pages.rohreinigung_wien_1150'); }
    public function rohreinigung_wien_1160() { return view('pages.rohreinigung_wien_1160'); }
    public function rohreinigung_wien_1170() { return view('pages.rohreinigung_wien_1170'); }
    public function rohreinigung_wien_1180() { return view('pages.rohreinigung_wien_1180'); }
    public function rohreinigung_wien_1190() { return view('pages.rohreinigung_wien_1190'); }
    public function rohreinigung_wien_1200() { return view('pages.rohreinigung_wien_1200'); }
    public function rohreinigung_wien_1210() { return view('pages.rohreinigung_wien_1210'); }
    public function rohreinigung_wien_1220() { return view('pages.rohreinigung_wien_1220'); }
    public function rohreinigung_wien_1230() { return view('pages.rohreinigung_wien_1230'); }
    public function rohreinigung_wiener_neustadt() { return view('pages.rohreinigung_wiener_neustadt'); }
    public function rohrverstopfung_baden() { return view('pages.rohrverstopfung_baden'); }
    public function rohrverstopfung_burgenland() { return view('pages.rohrverstopfung_burgenland'); }
    public function rohrverstopfung_graz() { return view('pages.rohrverstopfung_graz'); }
    public function rohrverstopfung_linz() { return view('pages.rohrverstopfung_linz'); }
    public function rohrverstopfung_niederosterreich() { return view('pages.rohrverstopfung_niederosterreich'); }
    public function rohrverstopfung_notdienst_baden() { return view('pages.rohrverstopfung_notdienst_baden'); }
    public function rohrverstopfung_notdienst_burgenland() { return view('pages.rohrverstopfung_notdienst_burgenland'); }
    public function rohrverstopfung_notdienst_graz() { return view('pages.rohrverstopfung_notdienst_graz'); }
    public function rohrverstopfung_notdienst_linz() { return view('pages.rohrverstopfung_notdienst_linz'); }
    public function rohrverstopfung_notdienst_niederosterreich() { return view('pages.rohrverstopfung_notdienst_niederosterreich'); }
    public function rohrverstopfung_notdienst_wien_1010() { return view('pages.rohrverstopfung_notdienst_wien_1010'); }
    public function rohrverstopfung_notdienst_wien_1020() { return view('pages.rohrverstopfung_notdienst_wien_1020'); }
    public function rohrverstopfung_notdienst_wien_1030() { return view('pages.rohrverstopfung_notdienst_wien_1030'); }
    public function rohrverstopfung_notdienst_wien_1040() { return view('pages.rohrverstopfung_notdienst_wien_1040'); }
    public function rohrverstopfung_notdienst_wien_1050() { return view('pages.rohrverstopfung_notdienst_wien_1050'); }
    public function rohrverstopfung_notdienst_wien_1060() { return view('pages.rohrverstopfung_notdienst_wien_1060'); }
    public function rohrverstopfung_notdienst_wien_1070() { return view('pages.rohrverstopfung_notdienst_wien_1070'); }
    public function rohrverstopfung_notdienst_wien_1080() { return view('pages.rohrverstopfung_notdienst_wien_1080'); }
    public function rohrverstopfung_notdienst_wien_1090() { return view('pages.rohrverstopfung_notdienst_wien_1090'); }
    public function rohrverstopfung_notdienst_wien_1100() { return view('pages.rohrverstopfung_notdienst_wien_1100'); }
    public function rohrverstopfung_notdienst_wien_1110() { return view('pages.rohrverstopfung_notdienst_wien_1110'); }
    public function rohrverstopfung_notdienst_wien_1120() { return view('pages.rohrverstopfung_notdienst_wien_1120'); }
    public function rohrverstopfung_notdienst_wien_1130() { return view('pages.rohrverstopfung_notdienst_wien_1130'); }
    public function rohrverstopfung_notdienst_wien_1140() { return view('pages.rohrverstopfung_notdienst_wien_1140'); }
    public function rohrverstopfung_notdienst_wien_1150() { return view('pages.rohrverstopfung_notdienst_wien_1150'); }
    public function rohrverstopfung_notdienst_wien_1160() { return view('pages.rohrverstopfung_notdienst_wien_1160'); }
    public function rohrverstopfung_notdienst_wien_1170() { return view('pages.rohrverstopfung_notdienst_wien_1170'); }
    public function rohrverstopfung_notdienst_wien_1180() { return view('pages.rohrverstopfung_notdienst_wien_1180'); }
    public function rohrverstopfung_notdienst_wien_1190() { return view('pages.rohrverstopfung_notdienst_wien_1190'); }
    public function rohrverstopfung_notdienst_wien_1200() { return view('pages.rohrverstopfung_notdienst_wien_1200'); }
    public function rohrverstopfung_notdienst_wien_1210() { return view('pages.rohrverstopfung_notdienst_wien_1210'); }
    public function rohrverstopfung_notdienst_wien_1220() { return view('pages.rohrverstopfung_notdienst_wien_1220'); }
    public function rohrverstopfung_notdienst_wien_1230() { return view('pages.rohrverstopfung_notdienst_wien_1230'); }
    public function rohrverstopfung_notdienst_wiener() { return view('pages.rohrverstopfung_notdienst_wiener'); }
    public function rohrverstopfung_wien_1010() { return view('pages.rohrverstopfung_wien_1010'); }
    public function rohrverstopfung_wien_1020() { return view('pages.rohrverstopfung_wien_1020'); }
    public function rohrverstopfung_wien_1030() { return view('pages.rohrverstopfung_wien_1030'); }
    public function rohrverstopfung_wien_1040() { return view('pages.rohrverstopfung_wien_1040'); }
    public function rohrverstopfung_wien_1040_2() { return view('pages.rohrverstopfung_wien_1040_2'); }
    public function rohrverstopfung_wien_1050() { return view('pages.rohrverstopfung_wien_1050'); }
    public function rohrverstopfung_wien_1060() { return view('pages.rohrverstopfung_wien_1060'); }
    public function rohrverstopfung_wien_1070() { return view('pages.rohrverstopfung_wien_1070'); }
    public function rohrverstopfung_wien_1080() { return view('pages.rohrverstopfung_wien_1080'); }
    public function rohrverstopfung_wien_1090() { return view('pages.rohrverstopfung_wien_1090'); }
    public function rohrverstopfung_wien_1100() { return view('pages.rohrverstopfung_wien_1100'); }
    public function rohrverstopfung_wien_1110() { return view('pages.rohrverstopfung_wien_1110'); }
    public function rohrverstopfung_wien_1120() { return view('pages.rohrverstopfung_wien_1120'); }
    public function rohrverstopfung_wien_1130() { return view('pages.rohrverstopfung_wien_1130'); }
    public function rohrverstopfung_wien_1140() { return view('pages.rohrverstopfung_wien_1140'); }
    public function rohrverstopfung_wien_1150() { return view('pages.rohrverstopfung_wien_1150'); }
    public function rohrverstopfung_wien_1160() { return view('pages.rohrverstopfung_wien_1160'); }
    public function rohrverstopfung_wien_1170() { return view('pages.rohrverstopfung_wien_1170'); }
    public function rohrverstopfung_wien_1180() { return view('pages.rohrverstopfung_wien_1180'); }
    public function rohrverstopfung_wien_1190() { return view('pages.rohrverstopfung_wien_1190'); }
    public function rohrverstopfung_wien_1200() { return view('pages.rohrverstopfung_wien_1200'); }
    public function rohrverstopfung_wien_1210() { return view('pages.rohrverstopfung_wien_1210'); }
    public function rohrverstopfung_wien_1220() { return view('pages.rohrverstopfung_wien_1220'); }
    public function rohrverstopfung_wien_1230() { return view('pages.rohrverstopfung_wien_1230'); }
    public function rohrverstopfung_wiener_neustadt() { return view('pages.rohrverstopfung_wiener_neustadt'); }
    public function services() { return view('pages.services'); }
    public function siphon_reinigen() { return view('pages.siphon_reinigen'); }
    public function toilette_verstopft() { return view('pages.toilette_verstopft'); }
    public function uber_uns() { return view('pages.uber_uns'); }
    public function verstopfter_abfluss_baden() { return view('pages.verstopfter_abfluss_baden'); }
    public function verstopfter_abfluss_burgenland() { return view('pages.verstopfter_abfluss_burgenland'); }
    public function verstopfter_abfluss_burgenland_2() { return view('pages.verstopfter_abfluss_burgenland_2'); }
    public function verstopfter_abfluss_graz() { return view('pages.verstopfter_abfluss_graz'); }
    public function verstopfter_abfluss_linz() { return view('pages.verstopfter_abfluss_linz'); }
    public function verstopfter_abfluss_niederosterreich() { return view('pages.verstopfter_abfluss_niederosterreich'); }
    public function verstopfter_abfluss_wien_1020() { return view('pages.verstopfter_abfluss_wien_1020'); }
    public function verstopfter_abfluss_wien_1030() { return view('pages.verstopfter_abfluss_wien_1030'); }
    public function verstopfter_abfluss_wien_1040() { return view('pages.verstopfter_abfluss_wien_1040'); }
    public function verstopfter_abfluss_wien_1050() { return view('pages.verstopfter_abfluss_wien_1050'); }
    public function verstopfter_abfluss_wien_1060() { return view('pages.verstopfter_abfluss_wien_1060'); }
    public function verstopfter_abfluss_wien_1070() { return view('pages.verstopfter_abfluss_wien_1070'); }
    public function verstopfter_abfluss_wien_1080() { return view('pages.verstopfter_abfluss_wien_1080'); }
    public function verstopfter_abfluss_wien_1090() { return view('pages.verstopfter_abfluss_wien_1090'); }
    public function verstopfter_abfluss_wien_1100() { return view('pages.verstopfter_abfluss_wien_1100'); }
    public function verstopfter_abfluss_wien_1110() { return view('pages.verstopfter_abfluss_wien_1110'); }
    public function verstopfter_abfluss_wien_1120() { return view('pages.verstopfter_abfluss_wien_1120'); }
    public function verstopfter_abfluss_wien_1130() { return view('pages.verstopfter_abfluss_wien_1130'); }
    public function verstopfter_abfluss_wien_1140() { return view('pages.verstopfter_abfluss_wien_1140'); }
    public function verstopfter_abfluss_wien_1150() { return view('pages.verstopfter_abfluss_wien_1150'); }
    public function verstopfter_abfluss_wien_1160() { return view('pages.verstopfter_abfluss_wien_1160'); }
    public function verstopfter_abfluss_wien_1170() { return view('pages.verstopfter_abfluss_wien_1170'); }
    public function verstopfter_abfluss_wien_1180() { return view('pages.verstopfter_abfluss_wien_1180'); }
    public function verstopfter_abfluss_wien_1190() { return view('pages.verstopfter_abfluss_wien_1190'); }
    public function verstopfter_abfluss_wien_1200() { return view('pages.verstopfter_abfluss_wien_1200'); }
    public function verstopfter_abfluss_wien_1210() { return view('pages.verstopfter_abfluss_wien_1210'); }
    public function verstopfter_abfluss_wien_1220() { return view('pages.verstopfter_abfluss_wien_1220'); }
    public function verstopfter_abfluss_wien_1230() { return view('pages.verstopfter_abfluss_wien_1230'); }
    public function verstopfter_abfluss_wiener_neustadt() { return view('pages.verstopfter_abfluss_wiener_neustadt'); }
    public function verstopfungsbehebung_wien_1010_2() { return view('pages.verstopfungsbehebung_wien_1010_2'); }
    public function verstopfungsbehebung_wien_1020() { return view('pages.verstopfungsbehebung_wien_1020'); }
    public function verstopfungsbehebung_wien_1030() { return view('pages.verstopfungsbehebung_wien_1030'); }
    public function verstopfungsbehebung_wien_1040() { return view('pages.verstopfungsbehebung_wien_1040'); }
    public function verstopfungsbehebung_wien_1050() { return view('pages.verstopfungsbehebung_wien_1050'); }
    public function verstopfungsbehebung_wien_1060() { return view('pages.verstopfungsbehebung_wien_1060'); }
    public function verstopfungsbehebung_wien_1070() { return view('pages.verstopfungsbehebung_wien_1070'); }
    public function verstopfungsbehebung_wien_1080() { return view('pages.verstopfungsbehebung_wien_1080'); }
    public function verstopfungsbehebung_wien_1090() { return view('pages.verstopfungsbehebung_wien_1090'); }
    public function verstopfungsbehebung_wien_1100() { return view('pages.verstopfungsbehebung_wien_1100'); }
    public function verstopfungsbehebung_wien_1110() { return view('pages.verstopfungsbehebung_wien_1110'); }
    public function verstopfungsbehebung_wien_1120() { return view('pages.verstopfungsbehebung_wien_1120'); }
    public function verstopfungsbehebung_wien_1130() { return view('pages.verstopfungsbehebung_wien_1130'); }
    public function verstopfungsbehebung_wien_1140() { return view('pages.verstopfungsbehebung_wien_1140'); }
    public function verstopfungsbehebung_wien_1150() { return view('pages.verstopfungsbehebung_wien_1150'); }
    public function verstopfungsbehebung_wien_1160() { return view('pages.verstopfungsbehebung_wien_1160'); }
    public function verstopfungsbehebung_wien_1170() { return view('pages.verstopfungsbehebung_wien_1170'); }
    public function verstopfungsbehebung_wien_1180() { return view('pages.verstopfungsbehebung_wien_1180'); }
    public function verstopfungsbehebung_wien_1190() { return view('pages.verstopfungsbehebung_wien_1190'); }
    public function verstopfungsbehebung_wien_1200() { return view('pages.verstopfungsbehebung_wien_1200'); }
    public function verstopfungsbehebung_wien_1210() { return view('pages.verstopfungsbehebung_wien_1210'); }
    public function verstopfungsbehebung_wien_1220() { return view('pages.verstopfungsbehebung_wien_1220'); }
    public function verstopfungsbehebung_wien_1230() { return view('pages.verstopfungsbehebung_wien_1230'); }
    public function vsaheading() { return view('pages.vsaheading'); }
    public function waschbecken_abfluss_reinigen() { return view('pages.waschbecken_abfluss_reinigen'); }
    public function wasserschaden() { return view('pages.wasserschaden'); }
    public function wc_abfluss_reinigen() { return view('pages.wc_abfluss_reinigen'); }
    public function wc_verstopft() { return view('pages.wc_verstopft'); }
}
